#
# docker network create --gateway 172.18.0.1 --subnet 172.18.0.0/16 redecommerce
#
version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  wordpress_data: {}

#
# Creating mysql connector
#

# curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "inventory-connector", "config": { "connector.class": "io.debezium.connector.mysql.MySqlConnector", "tasks.max": "1", "database.hostname": "mysql", "database.port": "3306", "database.user": "debezium", "database.password": "dbz", "database.server.id": "184054", "database.server.name": "dbserver1", "database.include.list": "inventory", "database.history.kafka.bootstrap.servers": "kafka:9092", "database.history.kafka.topic": "dbhistory.inventory" } }'

# Getting connectors
# curl -H "Accept:application/json" localhost:8083/connectors/

# Getting inventory-connector
# curl -i -X GET -H "Accept:application/json" localhost:8083/connectors/inventory-connector

